repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0  # Replace <version> with the desired version or use a commit SHA
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terrascan
